### ISSUE TITLE
Crear Filtros en pantalla "Gestión de pagos realizados"

### ISSUE THREAD

**Issue by alvarogarcia1010** [mgallegos/decima-purchase#53]

**Comment by mgallegos** [comment]
Mover columna de cuenta bancaria después de la columna de referencia.

**Comment by alvarogarcia1010** [comment]
Listo!

**Comment by mgallegos** [comment]
El campo "Pagado a" debe apuntar al autocomplete de **proveedores** y  lo de la cuenta bancaria me refería a la columna del grid.

**Comment by alvarogarcia1010** [comment]
Revisar!
