### ISSUE TITLE
En conf. inicial en la sección de requisiciones y compra, agregar checkbox: Generar número de cheque (check_number_is_generated)

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-purchase#55]

**Comment by alvarogarcia1010** [comment]
Listo! 
Tambien se agrego la función del journal a  casi todos los tokenfield! 
Quedan pendientes los 3 de usuario...

**Comment by mgallegos** [comment]
Revisa también:
-  tokenfield también cuando quedan vacíos
- journal de Bodega de consumibles
- journal de Mostar solo articulos con existencias (que el journal sea igual a la etiqueta)
- colocar como requerido el tamaño de papel de libro de compras
- revisar etiquetas de journal de campos de iva percepción y retención
- revisar etiqueta de journal de impuesto iva sobre compras, apunta a uno diferente.

**Comment by mgallegos** [comment]
Revisar:
 - Solo mostrar descuentos asociados a los productos y servicios
 - Impuestos a mostrar en libro como otros impuestos 
 - Cuenta contable de anticipo
