### ISSUE TITLE
En Gestión de Tipo de Documento agregar los siguientes autocompletes (todos son de tipo de movimiento): (1) Tipo de movimiento de inventario para aumentar existencias en compras (purchase_increase_movement_type_id), (2) Tipo de movimiento de inventario para disminuir existencias en compras (purchase_decrease_movement_type_id), (3) Tipo de movimiento de inventario para aumentar existencias en ventas (sale_increase_movement_type_id), (4) Tipo de movimiento de inventario para disminuir existencias en ventas (sale_drecrease_movement_type_id)

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-purchase#60]
Ejecutar script:

use `demo_decimaerp`;

ALTER TABLE `PURCH_Document_Type` 
ADD COLUMN `purchase_increase_movement_type_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `syncronized`,
ADD COLUMN `purchase_decrease_movement_type_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `purchase_increase_movement_type_id`,
ADD COLUMN `sale_increase_movement_type_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `purchase_decrease_movement_type_id`,
ADD COLUMN `sale_drecrease_movement_type_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `sale_increase_movement_type_id`,
ADD INDEX `pdt_sale_drecrease_movement_type_id_foreign_idx` (`sale_drecrease_movement_type_id` ASC),
ADD INDEX `pdt_purchase_increase_movement_type_id_foreign_idx` (`purchase_increase_movement_type_id` ASC),
ADD INDEX `pdt_sale_increase_movement_type_id_foreign_idx` (`sale_increase_movement_type_id` ASC),
ADD INDEX `pdt_purchase_decrease_movement_type_id_foreign_idx` (`purchase_decrease_movement_type_id` ASC);

**Comment by alvarogarcia1010** [comment]
Revisión!
