### ISSUE TITLE
Reporte de compra de artículos

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-purchase#66]
El grid debe tener las siguientes columnas:
- Las mismas del reporte de venta de artículos

Debe tener los siguientes filtros:
- Los mismo filtros de gestión de compras

Indicaciones:
- URL: /purchases/reports/article-purchases
- Nombre de la vista: article-purchases.blade.php
- Utilizar el prefijo: purch-ap-
- Utilizar como base el reporte plantilla de reportes del sistema.
- Dentro de la carpeta Repositories/Order/EloquentArticlePurchasesGridRepository
- Totalizar columna de cantidad y total.

**Comment by mgallegos** [comment]
Menú:

INSERT INTO `dev_decimaerp`.`SEC_Menu` (`name`, `lang_key`, `url`, `action_button_id`, `action_lang_key`, `icon`, `parent_id`, `created_by`, `module_id`) 
VALUES ('Article Purchases', 'decima-purchase::menu.articlePurchases', '/purchases/reports/article-purchases', '', 'decima-purchase::menu.articlePurchasesAction', 'fa fa-file-text-o', '99', '1', '8');

**Comment by mgallegos** [comment]
Restringir a 20 artículos por página que se muestren el grid, igual que el reporte de compras. Hacer lo mismo en el de ventas.

**Comment by mgallegos** [comment]
Realizar los siguientes ajustes:
- Agregar columna de fecha y proveedor (después de correlat.)
- Esconder al inicio columna de nombre alternativo y observación
- Agregar checkbox de Mostrar nombre alternativo y Mostrar observación.
- Alinear a la izquierda columna de tipo de documento

**Comment by alvarogarcia1010** [comment]
Issue listo para cerrar!
