### ISSUE TITLE
Reporte de cuentas por pagar a una fecha determinada

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-purchase#71]
El grid debe tener las siguientes columnas:
- Las mismas del reporte de compra de artículos
- Cambiar la última por Monto a pagar y agregar Monto pagado

Debe tener los siguientes filtros:
- Rango de fecha de registro
- Cuenta contable (autocomplete, dejálo vacío por el momento)

Indicaciones:
- URL: /purchases/reports/given-date-payable-accounts
- Nombre de la vista: given-date-payable-accounts.blade.php
- Utilizar el prefijo: purch-gdpa-
- Utilizar como base el reporte de compra de artículos
- Controlador: GivenDatePayableAccount
- Dentro de la carpeta Repositories/Order/EloquentGivenDatePayableAccountGridRepository
- Totalizar columna de Monto a pagar y Monto pagado.

Pendiente el menú

**Comment by mgallegos** [comment]
Menú:
```
INSERT INTO `dev_decimaerp`.`SEC_Menu` (`name`, `lang_key`, `url`, `action_button_id`, `action_lang_key`, `icon`, `parent_id`, `created_by`, `module_id`) 
VALUES ('Given Date Payable Accounts', 'decima-purchase::menu.givenDatePayableAccounts', '/purchases/reports/given-date-payable-accounts', '', 'decima-purchase::menu.givenDatePayableAccountsAction', 'fa fa-file-text-o', '99', '1', '8');

**Comment by alvarogarcia1010** [comment]
Solo falta que funcione el filtro de cuenta contable, y la consulta del monto pagado

**Comment by mgallegos** [comment]
Falta limpiar el controlador de todas las variables y servicios que no se están utilizando.
