### ISSUE TITLE
Ajustes en cuentas por pagar

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-purchase#88]
todo:
- Al seleccionar compras, mostrar a la derecha del toolbar un label de Total a pagar con la suma de las ventas seleccionadas.
- En la popup, mostrar una columna a la derecha, con las compras seleccionadas (fecha de emisión, proveedor, tipo de documento, número de doc., quedan, total a pagar, Abono (campo de texto).
- Dejar listo una función que arme un objeto con así: {id: $id, amount: $amount)
- Validar que la suma de todos los campo de texto coincidan con el total cobrado

Crear rama dev

**Comment by alvarogarcia1010** [comment]
Otra tablita con 3 columnas (Impuesto, Aplicar sobre, Monto Impuesto) aplicar sobre, es igual al total pagado, el impuesto es un autocomplete que se convierte en label (ver punto de ventas)  Monto del impuesto es en base a autocomplete de Impuesto.
